# -*- coding: utf-8 -*-
"""factorial_program.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B1cjI-ix2HhHk9Wc7aoVJgxhkGTKaRJS

d) Recursion (5 marks)
Write a recursive function to compute the factorial of a number entered by the user. Demonstrate the program using sample input and output.
"""

# A recursive function to compute the factorial of a number entered by the user
def factorial(n):
    if n == 0 or n == 1:
        return 1
    return n * factorial(n - 1)


num = int(input("Enter number: "))
print("Factorial =", factorial(num))