# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZpHZ6L7yt_NzVLh8lSrE2Vodr5fOQDHP
"""

class HashTable:
    def __init__(self, size):
        self.size = size
        self.table = [[] for _ in range(self.size)]

    def _hash(self, key):
        return hash(key) % self.size

    def insert(self, key, value):
        index = self._hash(key)
        for i, (k, v) in enumerate(self.table[index]):
            if k == key:
                self.table[index][i] = (key, value) # Update if key exists
                return
        self.table[index].append((key, value))

    def get(self, key):
        index = self._hash(key)
        for k, v in self.table[index]:
            if k == key:
                return v
        return None

    def display(self):
        for i, bucket in enumerate(self.table):
            print(f"Bucket {i}: {bucket}")

class Node:
    def __init__(self, key):
        self.key = key
        self.left = None
        self.right = None

class BST:
    def insert(self, root, key):
        if root is None:
            return Node(key)
        if key < root.key:
            root.left = self.insert(root.left, key)
        else:
            root.right = self.insert(root.right, key)
        return root

    def inorder(self, root):
        if root:
            self.inorder(root.left)
            print(root.key, end=" ")
            self.inorder(root.right)

class Graph:
    def __init__(self):
        self.graph = {}

    def add_edge(self, u, v):
        if u not in self.graph:
            self.graph[u] = []
        if v not in self.graph:
            self.graph[v] = []
        self.graph[u].append(v)
        # For an undirected graph, add the reverse edge as well
        # self.graph[v].append(u)

    def display(self):
        for node, neighbors in self.graph.items():
            print(f"{node}: {neighbors}")

def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)


print("=== HASH TABLE ===")
ht = HashTable(5)
ht.insert(101, "Alice")
ht.insert(106, "Bob")
ht.display()

print("\n=== BINARY SEARCH TREE ===")
tree = BST()
root = None
for name in ["John", "Alice", "Bob"]:
    root = tree.insert(root, name)

tree.inorder(root)

print("\n\n=== GRAPH ===")
g = Graph()
g.add_edge("A", "B")
g.add_edge("A", "C")
g.display()

print("\n=== FACTORIAL ===")
print("Factorial of 5:", factorial(5))