# -*- coding: utf-8 -*-
"""hash_table_program

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KUbPD4922stdhvy88HvxRh8heGSkl_Qt

a) Hash Table Implementation (5 marks)
Write a program to implement a simple hash table that stores student registration numbers and names. The program should:

Insert student records using registration number as the key.

Handle collisions using either chaining or linear probing.
"""

#Hash table using chaining

class HashTable:
    def __init__(self, size=4):
        self.size = size
        self.table = [[] for _ in range(self.size)]


    def hash_function(self, key):
        return key % self.size

    def insert(self, reg_no, name):
        index = self.hash_function(reg_no)
        self.table[index].append((reg_no, name))

    def display(self):
        for i, bucket in enumerate(self.table):
            print(i, ":", bucket)


# Test
ht = HashTable()

ht.insert(89, "Millie")
ht.insert(76, "James")
ht.insert(55, "Betty")

ht.display()