# -*- coding: utf-8 -*-
"""bst_program.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cVE7M53Qr2EO2cnp25Rnf7v7JXpm0TWt

b) Binary Search Tree Implementation (5 marks)
Write a program to implement a binary search tree that supports the following operations:

Insert a node

Search for a student name

Display the tree using in-order traversal
"""

class Node:
    def __init__(self, name):
        self.name = name
        self.left = None
        self.right = None


class BST:
    def insert(self, root, name):
        if root is None:
            return Node(name)

        if name < root.name:
            root.left = self.insert(root.left, name)
        else:
            root.right = self.insert(root.right, name)

        return root

    def search(self, root, name):
        if root is None or root.name == name:
            return root

        if name < root.name:
            return self.search(root.left, name)

        return self.search(root.right, name)

    def inorder(self, root):
        if root:
            self.inorder(root.left)
            print(root.name)
            self.inorder(root.right)


bst = BST()
root = None

root = bst.insert(root, "Millie")
root = bst.insert(root, "Jay")
root = bst.insert(root, "Joe")

print("Inorder traversal:")
bst.inorder(root)

print(bst.search(root, "Jay"))

