# -*- coding: utf-8 -*-
"""graph_program.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_7gxE7XujvLRy1K6gTHiD8AWFAXZ_9Q-

c) Graph Representation (5 marks)
Write a program to represent a graph using an adjacency list. Allow the user to:

Add edges between vertices

Display the graph
"""

# A program to represent a graph using an adjacency list
class Graph:
    def __init__(self):
        self.graph = {}

    def add_edge(self, d, c):
        if d not in self.graph:
            self.graph[d] = []
        if c not in self.graph:
            self.graph[c] = []

        self.graph[d].append(c)

    def display(self):
        for vertex in self.graph:
            print(vertex, "->", self.graph[vertex])


g = Graph()

g.add_edge("A", "B")
g.add_edge("A", "C")
g.add_edge("B", "D")
g.add_edge("D" ,"E")

g.display()